# Generated by Django 3.2.7 on 2021-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='', max_length=10)),
                ('category', models.CharField(default='', max_length=20)),
                ('color', models.CharField(default='', max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('product_count', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pd', models.CharField(max_length=50)),
            ],
        ),
    ]
