# Generated by Django 3.2.7 on 2021-11-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pd', models.CharField(max_length=50)),
                ('cpd', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
